### PR TITLE
updated step1 to provide conversion tables

### PR DESCRIPTION
**Pull request by EBosi**
#32 
This is my forked version, I hope everything works fine... please @franciscozorrilla test it and let me know.
You should produce conversion tables (tab separated files with a header) for each macromolecule class (dna, rna, proteins, etc).
Example:
```
$ cat dntps.conversion_table.txt
bigg_id	seed_id
dttp_c	cpd00357_c0
datp_c	cpd00115_c0
dctp_c	cpd00356_c0
dgtp_c	cpd00241_c0
ppi_c	cpd00012_c0
```
These comes in play when you compute the coefficients of the correspondent macromolecules. Here you have some lines as example: 
```
dna_coefficients = step1.generate_dna_coefficients(genome,model,DNA_WEIGHT_FRACTION=dna_weight_fraction,conversion_table="dntps.conversion_table.txt")

rna_coefficients = step1.generate_rna_coefficients(genbank,model,transcriptomic,RNA_WEIGHT_FRACTION=rna_weight_fraction,conversion_table="ntps.conversion_table.txt")

protein_coefficients = step1.generate_protein_coefficients(genbank,model,proteomic,PROTEIN_WEIGHT_FRACTION=protein_weight_fraction,conversion_table="aas.conversion_table.txt")
```
If I didn't mess with versions, fork, etc. it should all run smoothly (for me it did). If there are issues let me know and I will try to help more.
If instructions are unclear I can write a gist or whatever you need.

### CODE REVIEW

**Comment by franciscozorrilla** [comment]
@EBosi fantastic thanks! Do you think you could also provide me with all of your conversion tables if its not too much trouble? I will try this out soon

**Comment by EBosi** [comment]
Hi,
Yes I can... however they will likely differ from what you need... I might
share the scripts I used to generate them, perhaps it will be more useful!
Tomorrow I will try to share something!
Best
Emanuele

Il Lun 15 Apr 2019, 16:48 Francisco Zorrilla <notifications@github.com> ha
scritto:

**Comment by franciscozorrilla** [comment]
@EBosi thank you, the scripts would help!

**Comment by franciscozorrilla** [comment]
@EBosi please let me know if the scripts are somewhere in your repos! Thanks and best wishes.

**Comment by EBosi** [comment]
Hi,
Sorry I am away from pc for the easter break... I will try to send you
something asap

Il Mar 23 Apr 2019, 18:32 Francisco Zorrilla <notifications@github.com> ha
scritto:

**Comment by franciscozorrilla** [comment]
Scuza! Mi sono dimenticato che in Itialia sono le vacanze di pasqua! Take your time :)

**Comment by EBosi** [comment]
Hi Francisco, I'm back! :) 
I've pushed the script to create conversion tables, it should be decently commented, in case something doesn't work properly (or isn't clear), write me.
To make it work properly you should download the metanetx namespace files from https://www.metanetx.org/mnxdoc/mnxref.html

**Comment by jclachance** [comment]
@EBosi this si great work and a valuable addition to the package. I am merging it to the main branch and testing it. 

I am unsure of how to provide the conversion tables from MetaNetX. One option would be to include them in the "data" folder. The advantage I can see from this is that it will be 100% compatible. The flipside I see is, the tables are rather large and can add some unnecessary volume to the package. Also, I think MetaNetX does update these tables so it might just be better to properly lead users to their website for download.

**Comment by EBosi** [comment]
Hi, a possibility is to use the library urllib.
Example below:
```python
from urllib import urlopen
reader = urlopen("https://www.metanetx.org/cgi-bin/mnxget/mnxref/chem_prop.tsv")
```
In this way, the MetaNetX files don't have to be included in the repo, and the user will always use the updated version.
On the other hand, a connection is required (although it shouldn't be an issue).
If that's ok I can do some changes as soon as I have time.

**Comment by franciscozorrilla** [comment]
@EBosi thank you for sharing! I am wondering though, do I only need the chem_prop.tsv? or all 6 files?

@jclachance Using bash you could also wget the necessary files as part of the installation/setup process. 

`
wget https://www.metanetx.org/cgi-bin/mnxget/mnxref/chem_prop.tsv`

**Comment by EBosi** [comment]
you need chem_xref.tsv and comp_xref.tsv

**Comment by franciscozorrilla** [comment]
Thanks for the clarification @EBosi.

However, I have unsuccessfully attempted to generate the conversion tables. 
Below you can see the errors I get:

```
python metaNetX_xref_lib.py seed test/

wrong usage! RETRY!!
```

This seems strange, since the help file says that the function only needs two arguments, i.e. the last two are optional.

Next I tried specifying a model:

```
python metaNetX_xref_lib.py bigg test /c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoMerged.xml ./

Traceback (most recent call last):
  File "metaNetX_xref_lib.py", line 214, in <module>
    xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
NameError: name 'xref_handler' is not defined
```

I noticed that line 49 of metaNetX_xref_lib.py defines Xref_handler with a capital X, not lowercase as is written on line 214. 
```
line 49: class Xref_handler(object):
line 214: xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
```

I tried changing this around, but I am not very familiar with python and I just got a different error

```
python metaNetX_xref_lib.py bigg test /c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoMerged.xml ./
Traceback (most recent call last):
  File "metaNetX_xref_lib.py", line 214, in <module>
    xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
TypeError: unbound method biggBiomass2mnxs() must be called with xref_handler instance as first argument (got str instance instead)
```

I have ensured that the two required files are in the same directory as metaNetX_xref_lib.py. Do you have any idea as to what could be going wrong?

Thanks

**Comment by EBosi** [comment]
Hi Francisco,
sorry about that! I've tested and used the individual parts and it did work
for me, I've assembled all together in a single script but hadn't tested it
extensively...
I could fork some changes but it might take time, please try the following
changes in your local version and tell me how it works:

line 205: db,out_prefix = args[:2] -> if len(args) == 2: db,out_prefix =
args[:2]
line 206: if len(args) == 3: -> elif len(args) == 3:
line 212: xref = Xref_handler(*metanetx_xrefs) -> xref_handler =
Xref_handler(*metanetx_xrefs)

It should work fine! Sorry I didn't double checked it, hopefully it won't
give any error!
Best,
Emanuele

**Comment by franciscozorrilla** [comment]
Hey Emanuele,
No problem and thank you for the help!

Unfortunately after making the changes I still get the following:

```
python metaNetX_xref_lib.py seed ./ /c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoMerged.xml ./

Traceback (most recent call last):
  File "metaNetX_xref_lib.py", line 214, in <module>
    xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
NameError: name 'db' is not defined

```

Trying something with one less parameter:

```
python metaNetX_xref_lib.py chebi ./

WARNING: multiple elements found matching with ['16284', '10491', '14069', '19238', '42290', '495505', '61404'] in db chebi!
Only the last element will be returned!
Traceback (most recent call last):
  File "metaNetX_xref_lib.py", line 214, in <module>
    xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
  File "metaNetX_xref_lib.py", line 147, in biggBiomass2mnxs
    new_mets = self.translateBiggMetId(met,db,alternative_names=to_check,check_model=check_model)
  File "metaNetX_xref_lib.py", line 106, in translateBiggMetId
    new_loc = self.crossDbQuery("bigg",db,loc,type_="comp")
  File "metaNetX_xref_lib.py", line 76, in crossDbQuery
    except KeyError: raise KeyError("no equivalents of %s (mnx id: %s) found in %s" %(my_id,mnx_id,db2))
KeyError: 'no equivalents of c (mnx id: MNXC3) found in chebi'
```


Let me know if you have any further suggestions to fix this.
Best,
Francisco

**Comment by EBosi** [comment]
Hi Francisco,
sorry again, I took my time and made all relevant changes, I tested and it works for me... please use the version in my branch and tell me how it goes. I fixed the bug in the arguments specification and added the feature of getting metanetx data directly from the web... try to test that as well! (move/remove the xref files).

> However, I am now thinking that it may be best to just manually create these tables in my situation, since the model I am trying to generate a BOF for does not seem to follow any standard for the metabolite IDs.

It can be easier, and also safer, considering that you manually check your ids. I'm not sure which database you are using, but you should refer to the bigg ids used in bofdat and find the equivalent in your model. It's easier if you use MetaNetX (or bigg, e.g. http://bigg.ucsd.edu/universal/metabolites/10fthf). Let me know if you need advice or help.

Either way, can you test my script?   
Thanks
Emanuele

**Comment by franciscozorrilla** [comment]
Hey Emanuele,

Thanks for the help! 
Ok  I just replaced my metaNetX_xref_lib.py file with yours, that should be enough to test right?

It looks like the script doesnt work for the 'mnx' db option

```
python "/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat/metaNetX_xref_lib.py" mnx test ~/temp/BOFdat/modelHpoMerged.xml ./

Traceback (most recent call last):
  File "/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat/metaNetX_xref_lib.py", line 234, in <module>
    xref_handler.biggBiomass2mnxs(db,check_model=check_model,brute_force=is_brute_force)
  File "/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat/metaNetX_xref_lib.py", line 171, in biggBiomass2mnxs
    new_mets = self.translateBiggMetId(met,db,alternative_names=to_check,check_model=check_model)
  File "/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat/metaNetX_xref_lib.py", line 128, in translateBiggMetId
    new_met = self.crossDbQuery("bigg",db,met)
  File "/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat/metaNetX_xref_lib.py", line 99, in crossDbQuery
    except KeyError: raise KeyError("no equivalents of %s (mnx id: %s) found in %s" %(my_id,mnx_id,db2))
KeyError: 'no equivalents of datp (mnx id: MNXM286) found in mnx'
```

Trying with seed:

```
python metaNetX_xref_lib.py seed ./ ~/temp/BOFdat/modelHpoMerged.xml

WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00035', 'cpd01003'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00084', 'cpd00547'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00041', 'cpd19181'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00023', 'cpd19002', 'cpd27177'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00066', 'cpd01400'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00119', 'cpd00572'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00039', 'cpd19182'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00107', 'cpd15143'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00060', 'cpd30746'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00132', 'cpd15142'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00129', 'cpd15140'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00053', 'cpd00253'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00051', 'cpd19021'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00054', 'cpd30743'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00156', 'cpd15141'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00065', 'cpd19007'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['cpd00069', 'cpd30745'] in db seed!
All the elements will be returned
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
All the elements will be returned
```

And this results in empty conversion tables.

Next try without providing a model:

```
python metaNetX_xref_lib.py seed ./

WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00035', 'cpd01003'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00084', 'cpd00547'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00041', 'cpd19181'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00023', 'cpd19002', 'cpd27177'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00066', 'cpd01400'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00119', 'cpd00572'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00039', 'cpd19182'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00107', 'cpd15143'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00060', 'cpd30746'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00132', 'cpd15142'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00129', 'cpd15140'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00053', 'cpd00253'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00051', 'cpd19021'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00054', 'cpd30743'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00156', 'cpd15141'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00065', 'cpd19007'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['cpd00069', 'cpd30745'] in db seed!
Only the last element will be returned!
WARNING: multiple elements found matching with ['c', 'c0', 'cytosol'] in db seed!
Only the last element will be returned!
```

And this actually results in 3 conversion tables:

[ntps.conversion_table.txt](https://github.com/jclachance/BOFdat/files/3141452/ntps.conversion_table.txt)
[aas.conversion_table.txt](https://github.com/jclachance/BOFdat/files/3141453/aas.conversion_table.txt)
[dntps.conversion_table.txt](https://github.com/jclachance/BOFdat/files/3141454/dntps.conversion_table.txt)

I think I will manually edit these to fit my model, since I think this script will never work for models that dont strictly conform to a metabolite ID standard. For example, the model I am trying to get a BOF for has IDs like this:

`id="M_s_0955" name="L-alanine" compartment="c"`

What are your thoughts on this?

Here are examples of the type of models I am working with (from the systems and synthetic biology division of chalmers), if you want to take a look:

- https://github.com/SysBioChalmers/yeast-GEM
- https://github.com/SysBioChalmers/Yarrowia_lipolytica_W29-GEM
- https://github.com/SysBioChalmers/Streptomyces_coelicolor-GEM
- https://github.com/SysBioChalmers/rhto-GEM

Thanks again,
Francisco

**Comment by hariszaf** [comment]
Hi @EBosi and @jclachance . 
I am trying to run the `conversion_table` feature but it seems: 
 * it's not actually merged in the main repo 
 * i could not find any changes in the [` generate_coefficients`](https://github.com/EBosi/BOFdat/blob/master/BOFdat/core/dna.py#L75`) function, so how would it work? 

Many thanks in advance! 
And great great job! :+1:

**Pull request merged**
